MvcCarSalesSite/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcCarSalesSite.Models;

namespace MvcCarSalesSite.Controllers
{
    public class StatusController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Status
        public ActionResult Index()
        {
            return View(db.Statuses.ToList());
        }

        public PartialViewResult StatusList()
        {
            var status = db.Statuses.ToList();
            return PartialView(status);
        }


        // GET: Status/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Statuses.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // GET: Status/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Status/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StatusID,StatusName")] Status status)
        {
            if (ModelState.IsValid)
            {
                db.Statuses.Add(status);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(status);
        }

        // GET: Status/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Statuses.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // POST: Status/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StatusID,StatusName")] Status status)
        {
            if (ModelState.IsValid)
            {
                db.Entry(status).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(status);
        }

        // GET: Status/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Statuses.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Status status = db.Statuses.Find(id);
            db.Statuses.Remove(status);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcCarSalesSite/Views/Shared/LoginPartial.cshtml
<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
    @if (Request.IsAuthenticated)
    {
        if (this.User.IsInRole("admin"))
        {
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/Admin/Index/">Admin Paneli</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/Advert/Index/">@User.Identity.Name</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/Account/MyProfile/">Profilim</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-danger" aria-current="page" href="/Account/Logout/"><i class="bi bi-x-circle-fill"></i> Çıkış</a>
                <a class="btn btn-outline-info" aria-current="page" href="/Advert/Create/"><i class="bi bi-pencil"></i> İLAN VER</a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/Advert/Index/">@User.Identity.Name</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/Account/MyProfile/">Profilim</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-danger" aria-current="page" href="/Account/Logout/"><i class="bi bi-x-circle-fill"></i> Çıkış</a>
                <a class="btn btn-outline-info" aria-current="page" href="/Advert/Create/"><i class="bi bi-pencil"></i> İLAN VER</a>
            </li>
        }
    }
    else
    {
        <li class="nav-item">
            <a class="btn btn-outline-success" aria-current="page" href="/Account/Register/"><i class="bi bi-person-circle"></i> Üye Ol</a>
            <a class="btn btn-outline-primary" aria-current="page" href="/Account/Login/"><i class="bi bi-box-arrow-in-right"></i> Giriş</a>
            <a class="btn btn-outline-info" aria-current="page" href="/Account/Login/"><i class="bi bi-pencil"></i> İLAN VER</a>
        </li>
    }
</ul>

MvcCarSalesSite/Views/Shared/ModelPartial.cshtml
<option value="">Model Seç</option>
@if (ViewBag.mdllist != null)
{
	foreach (var item in ViewBag.mdllist)
	{
		<option value="@item.Value">@item.Text</option>
	}
}

MvcCarSalesSite/Views/Shared/SearchPartial.cshtml
@using (Html.BeginForm("Search", "Home", FormMethod.Get, new { @class = "d-flex" }))
{
        <input class="form-control me-2" type="search" placeholder="Arama" name="q" aria-label="Search">
        <button class="btn btn-outline-success col-sm-4" type="submit"><i class="bi bi-search"></i> Ara</button>
}

MvcCarSalesSite/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Araba Sitesi</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <!--MENÜ ÇUBUĞU-->
        <div class="container">
            <br />
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/Home/Index">
                        <img src="/Content/images/logo.png" width="60" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">

                        @Html.Partial("SearchPartial")

                        @Html.Action("StatusList","Status")

                       @Html.Partial("LoginPartial") 

                    </div>
                </div>
            </nav>
        </div>
    </header>

    @RenderBody()

    <footer>
        <!--footer-->
        <div class="container">
            <br />
            <div class="row" style="background-color: black">
                <div class="col-md-1">

                </div>
                <div class="col-md-8">
                    <h6 style="color:white; padding:15px 0px 0px 0px">İLETİŞİM</h6>
                    <ul class="list-unstyled">
                        <li><a href="/Account/Login/" style="color:white; text-decoration:none">GİRİŞ</a></li>
                        <li><a href="/Account/Register/" style="color:white; text-decoration:none">ÜYE OL</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <h6 style="color:white; padding:15px 0px 0px 0px">SOSYAL MEDYA</h6>
                    <ul class="list-unstyled">
                        <li>
                            <a href="https://tr-tr.facebook.com"><img src="/Content/images/facebook.png" width="50" /></a>
                            <a href="https://twitter.com/?lang=tr"><img src="~/Content/images/twitter.png" width="50" /></a>
                            <a href="https://www.instagram.com"><img src="~/Content/images/instagram.png" width="50" /></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>