MvcCarSalesSite/Controllers/AdminController.cs
using MvcCarSalesSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace MvcCarSalesSite.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        DataContext db = new DataContext();
        // GET: Admin
        public ActionResult Index()
        {          
            return View();
        }

        public ActionResult AdvertList()
        {
            var advert = db.Adverts.Include(x => x.Model).Include(x => x.Status).Include(x => x.City).ToList();
            return View(advert);
        }
    }
}

MvcCarSalesSite/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcCarSalesSite.Models;

namespace MvcCarSalesSite.Controllers
{
    public class BrandController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Brand
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: Brand/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BrandID,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BrandID,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: Brand/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcCarSalesSite/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcCarSalesSite.Models;

namespace MvcCarSalesSite.Controllers
{
    public class CityController : Controller
    {
        private DataContext db = new DataContext();

        // GET: City
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

        // GET: City/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: City/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: City/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CityID,CityName")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: City/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: City/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CityID,CityName")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: City/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: City/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcCarSalesSite/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcCarSalesSite.Models;

namespace MvcCarSalesSite.Controllers
{
    public class ModelController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Model
        public ActionResult Index()
        {
            var models = db.Models.Include(m => m.Brand);
            return View(models.ToList());
        }

        // GET: Model/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: Model/Create
        public ActionResult Create()
        {
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName");
            return View();
        }

        // POST: Model/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ModelID,ModelName,BrandID")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Models.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", model.BrandID);
            return View(model);
        }

        // GET: Model/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", model.BrandID);
            return View(model);
        }

        // POST: Model/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ModelID,ModelName,BrandID")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", model.BrandID);
            return View(model);
        }

        // GET: Model/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Model/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Models.Find(id);
            db.Models.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcCarSalesSite/Views/Admin/AdvertList.cshtml
@model IEnumerable<MvcCarSalesSite.Models.Advert>
@{
    ViewBag.Title = "AdvertList";
}

<div class="container">
    <br />

    <div class="row">     

        <div class="col-md-12">
            <!--bootstrap -> components -> breadcumb -> ortadaki kod kısmı-->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/Admin/Index/">Admin Sayfası</a></li>
                    <li class="breadcrumb-item active" aria-current="page">İlan Listesi</li>
                </ol>
            </nav>
            <div class="img-thumbnail">
                <br />

                <table class="table">
                    <tr>
                        <th>
                            Kullanıcı Adı
                        </th>
                        <th>
                            Marka
                        </th>
                        <th>
                            Model
                        </th>
                        <th>
                            Durum
                        </th>
                        <th>
                            Şehir
                        </th>
                        <th>
                            Fiyat
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <label class="btn btn-primary">@item.Username</label>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Model.Brand.BrandName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Model.ModelName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status.StatusName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City.CityName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                <a class="btn btn-danger" href="/Advert/Delete/@item.AdvertID"><i class="bi bi-trash"></i> Sil</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

MvcCarSalesSite/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <br />

    <div class="row">

        <!--bootstrap -> components -> breadcumb -> ortadaki kod kısmı-->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/Admin/Index/">Admin Sayfası</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ana Sayfa</li>
            </ol>
        </nav>
        <div class="col-md-2">
            <div class="img-thumbnail">
                <br />
                <img src="~/Content/images/statistics.jpg" width="130" height="75" />
                <p>@Html.ActionLink("İlan Listesi", "AdvertList", "Admin", null, new { @class = "btn btn-primary" })</p>
            </div>
        </div>

        <div class="col-md-2">
            <div class="img-thumbnail">
                <br />
                <img src="~/Content/images/statistics.jpg" width="130" height="75" />
                <p>@Html.ActionLink("Şehir Listesi", "Index", "City", null, new { @class = "btn btn-success" })</p>
            </div>
        </div>

        <div class="col-md-2">
            <div class="img-thumbnail">
                <br />
                <img src="~/Content/images/statistics.jpg" width="130" height="75" />
                <p>@Html.ActionLink("Durum Listesi", "Index", "Status", null, new { @class = "btn btn-info" })</p>
            </div>
        </div>

        <div class="col-md-2">
            <div class="img-thumbnail">
                <br />
                <img src="~/Content/images/statistics.jpg" width="130" height="75" />
                <p>@Html.ActionLink("Marka Listesi", "Index", "Brand", null, new { @class = "btn btn-warning" })</p>
            </div>
        </div>

        <div class="col-md-2">
            <div class="img-thumbnail">
                <br />
                <img src="~/Content/images/statistics.jpg" width="130" height="75" />
                <p>@Html.ActionLink("Model Listesi", "Index", "Model", null, new { @class = "btn btn-success" })</p>
            </div>
        </div>

    </div>

</div>