MvcCarSalesSite/Models/Advert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcCarSalesSite.Models
{
    public class Advert
    {
        public int AdvertID { get; set; }
        public string AdvertNo { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string AdvertDate { get; set; }
        public int Kilometer { get; set; }
        public int ModelYear { get; set; }
        public string FuelType { get; set; }
        public string GearType { get; set; }
        public string Username { get; set; }
        public string Phone { get; set; }
        public int StatusID { get; set; }
        public Status Status { get; set; }

        public int BrandID { get; set; }
        public int ModelID { get; set; }
        public Model Model { get; set; }

        public int CityID { get; set; }
        public City City { get; set; }

        public List<Picture> Pictures { get; set; }
    }
}

MvcCarSalesSite/Controllers/AdvertController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcCarSalesSite.Models;

namespace MvcCarSalesSite.Controllers
{
    public class AdvertController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Advert
        public ActionResult Index()
        {
            var username = User.Identity.Name;
            var adverts = db.Adverts.Where(x=>x.Username == username).Include(a => a.City).Include(a => a.Model).Include(a => a.Status);
            return View(adverts.ToList());
        }

        public List<Brand> BringBrand()
        {
            List<Brand> brands = db.Brands.ToList();
            return brands;
        }

        public ActionResult BringModel(int BrandID)
        {
            List<Model> modellist = db.Models.Where(x => x.BrandID == BrandID).ToList();
            ViewBag.mdllist = new SelectList(modellist, "ModelID", "ModelName");
            return PartialView("ModelPartial");
        }

        // GET: Advert/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            return View(advert);
        }

        // GET: Advert/Create
        public ActionResult Create()
        {
            ViewBag.brdlist = new SelectList(BringBrand(), "BrandID", "BrandName");
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName");
            ViewBag.StatusID = new SelectList(db.Statuses, "StatusID", "StatusName");
            return View();
        }

        public ActionResult Images(int id)
        {
            var advert = db.Adverts.Where(x => x.AdvertID == id).ToList();
            var imgs = db.Pictures.Where(x=>x.AdvertID == id).ToList();
            ViewBag.imgs = imgs;
            ViewBag.advert = advert;
            return View();
        }

        [HttpPost]
        public ActionResult Images(int id, HttpPostedFileBase file)
        {
            string path = Path.Combine("/Content/images/" + file.FileName);
            file.SaveAs(Server.MapPath(path));
            Picture pct = new Picture();
            pct.PictureName = file.FileName.ToString();
            pct.AdvertID = id;
            db.Pictures.Add(pct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Advert/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdvertID,AdvertNo,Description,Price,AdvertDate,Kilometer,ModelYear,FuelType,GearType,Username,Phone,StatusID,BrandID,ModelID,CityID")] Advert advert)
        {
            if (ModelState.IsValid)
            {
                advert.Username = User.Identity.Name;
                db.Adverts.Add(advert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.brdlist = new SelectList(BringBrand(), "BrandID", "BrandName");
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName", advert.CityID);           
            ViewBag.StatusID = new SelectList(db.Statuses, "StatusID", "StatusName", advert.StatusID);
            return View(advert);
        }

        // GET: Advert/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            ViewBag.brdlist = new SelectList(BringBrand(), "BrandID", "BrandName");
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName", advert.CityID);
            ViewBag.ModelID = new SelectList(db.Models, "ModelID", "ModelName", advert.ModelID);
            ViewBag.StatusID = new SelectList(db.Statuses, "StatusID", "StatusName", advert.StatusID);
            return View(advert);
        }

        // POST: Advert/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdvertID,AdvertNo,Description,Price,AdvertDate,Kilometer,ModelYear,FuelType,GearType,Username,Phone,StatusID,BrandID,ModelID,CityID")] Advert advert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(advert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName", advert.CityID);
            ViewBag.brdlist = new SelectList(BringBrand(), "BrandID", "BrandName");
            ViewBag.StatusID = new SelectList(db.Statuses, "StatusID", "StatusName", advert.StatusID);
            return View(advert);
        }

        // GET: Advert/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            return View(advert);
        }

        // POST: Advert/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advert advert = db.Adverts.Find(id);
            db.Adverts.Remove(advert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcCarSalesSite/Views/Advert/Create.cshtml
@model MvcCarSalesSite.Models.Advert

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Username, "Kullanıcı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-1">
                        <label class="btn btn-success">@User.Identity.Name</label>
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.AdvertNo, "İlan No", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.AdvertNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdvertNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Description, "Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Price, "Fiyat", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.AdvertDate, "Tarih", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.AdvertDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdvertDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Kilometer, "Kilometre", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Kilometer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Kilometer, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.ModelYear, "Model Yılı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.ModelYear, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ModelYear, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.FuelType, "Yakıt Türü", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.FuelType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FuelType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.GearType, "Vites Türü", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.GearType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GearType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Phone, "Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.StatusID, "Durum Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownList("StatusID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.BrandID, "Marka Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @if (ViewBag.brdlist != null)
                        {
                            @Html.DropDownListFor(x => x.BrandID, ViewBag.brdlist as SelectList, "Marka Seç", new { @class = "form-control" })
                        }
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.ModelID, "Model Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.ModelID, new SelectList(""), "Model Seç", new { @class = "form-control" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.CityID, "Şehir", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    <div class="col-md-offset-2 col-md-6">
                        <button type="submit" class="btn btn-outline-primary"><i class="bi bi-plus-circle"></i> Ekle</button>
                        <a href="/Advert/Index/" class="btn btn-outline-warning"><i class="bi bi-file-earmark"></i> İlan Listesi</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $("#BrandID").change(function () {
            var brandId = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Advert/BringModel?BrandID=" + brandId,
                contentType: "html",
                success: function (response) {
                    debugger
                    $("#ModelID").empty();
                    $("#ModelID").append(response);
                }
            })
        })
    })
</script>

MvcCarSalesSite/Views/Advert/Delete.cshtml
@model MvcCarSalesSite.Models.Advert

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h3>Bu ilanı silmek istediğinizden emin misiniz?</h3>
    <div>
        <dl class="dl-horizontal">
            <dt>
                İlan No
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AdvertNo)
            </dd>

            <dt>
                Açıklama
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                Fiyat
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                Tarih
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AdvertDate)
            </dd>

            <dt>
                Kilometre
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kilometer)
            </dd>

            <dt>
                Model Yılı
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModelYear)
            </dd>

            <dt>
                Yakıt Türü
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FuelType)
            </dd>

            <dt>
                Vites Türü
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GearType)
            </dd>

            <dt>
                Telefon
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <button type="submit" class="btn btn-outline-danger"><i class="bi bi-trash"></i> Sil</button>
        <a href="/Advert/Index/" class="btn btn-outline-warning"><i class="bi bi-file-earmark"></i> İlan Listesi</a>
    </div>
        }
    </div>
</div>

MvcCarSalesSite/Views/Advert/Details.cshtml
@model MvcCarSalesSite.Models.Advert

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Advert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdvertNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdvertNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdvertDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdvertDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kilometer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kilometer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuelType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GearType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GearType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrandID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AdvertID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcCarSalesSite/Views/Advert/Edit.cshtml
@model MvcCarSalesSite.Models.Advert

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="row">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(x=>x.AdvertID)

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Username, "Kullanıcı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.AdvertNo, "İlan No", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.AdvertNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdvertNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Description, "Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Price, "Fiyat", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.AdvertDate, "Tarih", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.AdvertDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdvertDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Kilometer, "Kilometre", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Kilometer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Kilometer, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.ModelYear, "Model Yılı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.ModelYear, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ModelYear, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.FuelType, "Yakıt Türü", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.FuelType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FuelType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.GearType, "Vites Türü", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.GearType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GearType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.Phone, "Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.StatusID, "Durum Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownList("StatusID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.BrandID, "Marka Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @if (ViewBag.brdlist != null)
                        {
                            @Html.DropDownListFor(x => x.BrandID, ViewBag.brdlist as SelectList, "Marka Seç", new { @class = "form-control" })
                        }
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.ModelID, "Model Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownList("ModelID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ModelID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    @Html.LabelFor(model => model.CityID, "Şehir", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3" style="text-align:center">
                    <div class="col-md-offset-2 col-md-6">
                        <button type="submit" class="btn btn-outline-primary"><i class="bi bi-pencil"></i> Düzenle</button>
                        <a href="/Advert/Index/" class="btn btn-outline-warning"><i class="bi bi-file-earmark"></i> İlan Listesi</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $("#BrandID").change(function () {
            var brandId = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Advert/BringModel?BrandID=" + brandId,
                contentType: "html",
                success: function (response) {
                    debugger
                    $("#ModelID").empty();
                    $("#ModelID").append(response);
                }
            })
        })
    })
</script>

MvcCarSalesSite/Views/Advert/Images.cshtml
@{
    ViewBag.Title = "Images";
}

<div class="container">
    @{ 
        Html.BeginForm("Images", "Advert", FormMethod.Post, new { enctype = "multipart/form-data" });
        foreach (var item in ViewBag.advert)
        {
            <h3>@item.AdvertID Numaralı İlan İçin Resim Ekle</h3>
            <table>
                <tr>
                    <td>Resim Seç</td>
                    <td><input type="hidden" name="id" value="@item.AdvertID"/></td>
                    <td><input type="file" name="file"/></td>
                    <td><input type="submit" value="Ekle" class="btn btn-primary"/></td>
                    <td><a href="/Advert/Index/" class="btn btn-outline-warning"><i class="bi bi-file-earmark"></i> İlan Listesi</a></td>
                </tr>
            </table>
        }
    }
    <br />
    <div class="row">
        @foreach (var item in ViewBag.imgs)
        {
            <div class="col-md-4">
                <div class="img-thumbnail">
                    <img src="~/Content/images/@item.PictureName" style="height:250px; width:100%"/>
                </div>
            </div>
        }
    </div>
</div>